version: "3.8"

services:
  shelly-rebooter:
    build: .
    container_name: shelly-rebooter
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
