version: "3.8"

services:
  shelly-rebooter:
    build: .
    container_name: shelly-rebooter
    ports:
      - "${PORT:-443}:${PORT:-443}"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./certs:/app/certs
